name: $APP_NAME

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
      args:
        - USER=${CONTAINER_USER:-user}
        - UID=${HOST_UID:-1000}
        - GID=${HOST_GID:-${HOST_UID:-1000}}
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - .:/app
      - /app/node_modules
